Fix: CI - Trigger release workflow after fast-forward merge

diff --git a/.github/workflows/fast-forward.yml b/.github/workflows/fast-forward.yml
--- a/.github/workflows/fast-forward.yml
+++ b/.github/workflows/fast-forward.yml
@@ -39,3 +39,58 @@ jobs:
           # never post a comment.  (In all cases the information is
           # still available in the step's summary.)
           comment: always
+
+      - name: Check target branch
+        if: ${{ steps.check_comment.outputs.MATCH == 'true' }}
+        id: check_branch
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          # From https://github.com/sequoia-pgp/fast-forward/blob/main/src/fast-forward.sh
+          PR_URL="${{ github.event.issue.pull_request.url }}"
+          if test "x$PR_URL" = x
+          then
+            echo "Unable to find pull request's context."
+            exit 1
+          fi
+
+          GITHUB_PR=$(mktemp)
+          function get_pr_info {
+            # https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request
+            curl --silent --show-error --location \
+                 -X GET \
+                 -H "Accept: application/vnd.github+json" \
+                 -H "Authorization: Bearer $GITHUB_TOKEN" \
+                 -H "X-GitHub-Api-Version: 2022-11-28" \
+                 "$PR_URL" >$GITHUB_PR
+          }
+
+          function check_pr_merged {
+            local merged_status="false"
+            local attempt=1
+            local max_attempts=30
+            local sleep_duration=1
+
+            while [ "$merged_status" != "true" ] && [ $attempt -le $max_attempts ]; do
+              get_pr_info
+              merged_status=$(jq -r ".merged" <$GITHUB_PR)
+
+              if [ "$merged_status" = "true" ]; then
+                break
+              else
+                sleep $sleep_duration
+                ((attempt++))
+              fi
+            done
+
+            if [ $attempt -gt $max_attempts ]; then
+              echo "The maximum number of attempts has been reached. The pull request was not merged."
+              exit 1
+            fi
+          }
+
+          get_pr_info
+          BASE_REF=$(jq -r ".base.ref" <$GITHUB_PR)
+          if [ "$BASE_REF" = "main" ]; then
+            check_pr_merged
+          fi
