Chore: Combine fast forward and release workflows again #69

diff --git a/.github/workflows/fast-forward.yml b/.github/workflows/fast-forward.yml
--- a/.github/workflows/fast-forward.yml
+++ b/.github/workflows/fast-forward.yml
@@ -1,4 +1,4 @@
-name: fast-forward
+name: fast-forward and release
 on:
   issue_comment:
     types: [created, edited]
@@ -14,6 +14,9 @@ jobs:
       pull-requests: write
       issues: write
 
+    outputs:
+      should_run: ${{ steps.check_branch.outputs.should_run }}
+
     steps:
       - name: Fast forwarding
         uses: sequoia-pgp/fast-forward@v1
@@ -24,3 +27,65 @@ jobs:
           # never post a comment.  (In all cases the information is
           # still available in the step's summary.)
           comment: always
+
+      - name: Check target branch
+        id: check_branch
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          # From https://github.com/sequoia-pgp/fast-forward/blob/main/src/fast-forward.sh
+          PR_URL="${{ github.event.issue.pull_request.url }}"
+          if test "x$PR_URL" = x
+          then
+            echo "Unable to find pull request's context."
+            exit 1
+          fi
+
+          GITHUB_PR=$(mktemp)
+          curl --silent --show-error --location \
+                 -X GET \
+                 -H "Accept: application/vnd.github+json" \
+                 -H "Authorization: Bearer $GITHUB_TOKEN" \
+                 -H "X-GitHub-Api-Version: 2022-11-28" \
+                 "$PR_URL" >$GITHUB_PR
+
+          BASE_REF=$(jq -r ".base.ref" <$GITHUB_PR)
+          if [ "$BASE_REF" = "main" ]; then
+            echo "should_run=true" >> $GITHUB_OUTPUT
+          else
+            echo "should_run=false" >> $GITHUB_OUTPUT
+          fi
+
+  release:
+    name: Release
+    needs: fast-forward
+    if: needs.fast-forward.outputs.should_run == 'true'
+
+    runs-on: ubuntu-latest
+    # https://docs.github.com/ko/actions/writing-workflows/workflow-syntax-for-github-actions#permissions
+    permissions:
+      contents: write
+      packages: write
+      pull-requests: write
+
+    steps:
+      - name: Checkout Repo
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Setup
+        uses: ./.github/actions/node-setup
+
+      - name: Create Release Pull Request or Publish to npm
+        id: changesets
+        uses: changesets/action@v1
+        with:
+          commit: "Chore: Version Packages"
+          publish: yarn run publish
+          version: yarn run version
+          setupGitUser: true
+          createGithubReleases: true
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
